### ISSUE TITLE
Questions about function device

### ISSUE THREAD

**Issue by siqandressa** [Komzpa/fidelity#1]
Hi my friend,
Whats this function "GetDevices(dbus_interface = self.NM)" do? I'm not to find a answer for this question in Google.

**Comment by Komzpa** [comment]
@siqandressa It is NetworkManager call to get list of user's network cards, see https://developer.gnome.org/NetworkManager/unstable/spec.html#org.freedesktop.NetworkManager

**Comment by siqandressa** [comment]
Thanks a lot @Komzpa !!!!

**Comment by Komzpa** [comment]
you're welcome.
